---
- become: true
  gather_facts: true
  hosts: all
  name: Converge
  pre_tasks:
  - ansible.builtin.apt:
      cache_valid_time: 600
      update_cache: true
    name: Update apt cache.
    when: ansible_os_family == 'Debian'
  roles:
  - role: buluma.kernel
